#!/bin/bash
cd /home/vpc/xprojects/base-world/commons/tson/modules/tson-parser-javacc/src/main/java/net/thevpc/tson/impl/parser/javacc/
# javacc-javacc-7.0.13
java -classpath /home/vpc/programs/dev/javacc/bootstrap/javacc.jar javacc tson_v06.jj
