/* Generated By:JavaCC: Do not edit this line. TsonStreamParserImplTokenManager.java */
package net.thevpc.tson.impl.parser.javacc;
import net.thevpc.tson.impl.parser.*;
import net.thevpc.tson.*;

/** Token Manager. */
public class TsonStreamParserImplTokenManager implements TsonStreamParserImplConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xa0000000000L) != 0L)
            return 147;
         if ((active0 & 0x8070000000L) != 0L)
         {
            jjmatchedKind = 45;
            return 188;
         }
         return -1;
      case 1:
         if ((active0 & 0x8070000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 1;
            return 188;
         }
         return -1;
      case 2:
         if ((active0 & 0x8000000000L) != 0L)
            return 188;
         if ((active0 & 0x70000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 2;
            return 188;
         }
         return -1;
      case 3:
         if ((active0 & 0x50000000L) != 0L)
            return 188;
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 3;
            return 188;
         }
         return -1;
      case 4:
         if ((active0 & 0x20000000L) != 0L)
            return 188;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 31);
      case 41:
         return jjStopAtPos(0, 32);
      case 43:
         return jjMoveStringLiteralDfa1_0(0x50000000000L);
      case 44:
         return jjStopAtPos(0, 36);
      case 45:
         return jjMoveStringLiteralDfa1_0(0xa0000000000L);
      case 58:
         return jjStopAtPos(0, 35);
      case 64:
         return jjStopAtPos(0, 37);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x8000000000L);
      case 91:
         return jjStopAtPos(0, 33);
      case 93:
         return jjStopAtPos(0, 34);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 123:
         return jjStopAtPos(0, 5);
      case 125:
         return jjStopAtPos(0, 6);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 66:
         return jjMoveStringLiteralDfa2_0(active0, 0xc0000000000L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x30000000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8020000000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 39, 188);
         break;
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x60000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x30000000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0000000000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 28, 188);
         break;
      case 102:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(3, 40);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(3, 41);
         break;
      case 108:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 188);
         break;
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0xc0000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 188);
         break;
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0xc0000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(5, 42);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(5, 43);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 188;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 147:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(134, 135);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(118, 119);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 10)
                        kind = 10;
                     jjCheckNAdd(117);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(115, 116);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(113, 114);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(111, 112);
                  if (curChar == 48)
                     jjCheckNAdd(182);
                  if (curChar == 48)
                     jjCheckNAdd(180);
                  if (curChar == 48)
                     jjCheckNAdd(175);
                  if (curChar == 48)
                     jjCheckNAdd(171);
                  if (curChar == 48)
                     jjCheckNAdd(169);
                  if (curChar == 48)
                     jjCheckNAdd(164);
                  if (curChar == 48)
                     jjCheckNAdd(160);
                  if (curChar == 48)
                     jjCheckNAdd(158);
                  if (curChar == 48)
                     jjCheckNAdd(153);
                  if (curChar == 48)
                     jjCheckNAdd(150);
                  if (curChar == 48)
                     jjCheckNAdd(149);
                  if (curChar == 48)
                     jjCheckNAdd(145);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 10)
                        kind = 10;
                     jjCheckNAddStates(0, 15);
                  }
                  else if (curChar == 45)
                     jjCheckNAddStates(16, 33);
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 44;
                  else if (curChar == 36)
                  {
                     if (kind > 45)
                        kind = 45;
                     jjCheckNAddTwoStates(39, 40);
                  }
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 33;
                  else if (curChar == 39)
                     jjAddStates(34, 35);
                  else if (curChar == 34)
                     jjCheckNAddStates(36, 38);
                  else if (curChar == 46)
                     jjCheckNAdd(6);
                  if (curChar == 48)
                     jjCheckNAddStates(39, 42);
                  else if (curChar == 47)
                     jjCheckNAddStates(43, 45);
                  if (curChar == 48)
                     jjCheckNAddStates(46, 53);
                  break;
               case 188:
                  if ((0x3ff001000000000L & l) != 0L)
                  {
                     if (kind > 45)
                        kind = 45;
                     jjCheckNAddTwoStates(39, 40);
                  }
                  else if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 2:
                  if ((0xfffffffffffffbffL & l) != 0L)
                     jjCheckNAddStates(43, 45);
                  break;
               case 3:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddStates(43, 45);
                  break;
               case 4:
                  if (curChar == 47 && kind > 4)
                     kind = 4;
                  break;
               case 5:
                  if (curChar == 46)
                     jjCheckNAdd(6);
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(6, 7);
                  break;
               case 8:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(9);
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAdd(9);
                  break;
               case 10:
                  if (curChar == 34)
                     jjCheckNAddStates(36, 38);
                  break;
               case 11:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(36, 38);
                  break;
               case 13:
                  if ((0x8400002400L & l) != 0L)
                     jjCheckNAddStates(36, 38);
                  break;
               case 14:
                  if (curChar == 34 && kind > 26)
                     kind = 26;
                  break;
               case 15:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(54, 57);
                  break;
               case 16:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(36, 38);
                  break;
               case 17:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 18:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 19:
                  if (curChar == 10)
                     jjCheckNAddStates(36, 38);
                  break;
               case 20:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 39)
                     jjAddStates(34, 35);
                  break;
               case 22:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAdd(23);
                  break;
               case 23:
                  if (curChar == 39 && kind > 27)
                     kind = 27;
                  break;
               case 25:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(23);
                  break;
               case 26:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(27, 23);
                  break;
               case 27:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(23);
                  break;
               case 28:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(27);
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(58, 59);
                  break;
               case 33:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(34, 36);
                  break;
               case 34:
                  if ((0xfffffffffffffffeL & l) != 0L)
                     jjCheckNAddTwoStates(34, 36);
                  break;
               case 35:
                  if (curChar == 47 && kind > 44)
                     kind = 44;
                  break;
               case 36:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 38:
                  if (curChar != 36)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAddTwoStates(39, 40);
                  break;
               case 39:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAddTwoStates(39, 40);
                  break;
               case 40:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 41:
                  if (curChar != 36)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAddTwoStates(40, 42);
                  break;
               case 42:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAddTwoStates(40, 42);
                  break;
               case 43:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if (curChar != 36)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddTwoStates(45, 46);
                  break;
               case 45:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddTwoStates(45, 46);
                  break;
               case 46:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 47:
                  if (curChar != 36)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddTwoStates(46, 48);
                  break;
               case 48:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddTwoStates(46, 48);
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddStates(0, 15);
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 58:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 62:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(60, 62);
                  break;
               case 68:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(63, 65);
                  break;
               case 71:
                  if ((0x280000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 75:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) != 0L && kind > 1)
                     kind = 1;
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(66, 74);
                  break;
               case 78:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(70, 71);
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(75, 77);
                  break;
               case 80:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(78, 81);
                  break;
               case 81:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(82, 86);
                  break;
               case 82:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(87, 92);
                  break;
               case 83:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(93, 99);
                  break;
               case 84:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(100, 107);
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 86:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 87:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 88:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 89:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 91:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 92:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 93:
                  if ((0x3ff000000000000L & l) != 0L && kind > 2)
                     kind = 2;
                  break;
               case 94:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 95:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 96:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 97:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 98:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 99:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 100:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 101:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 102:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 103:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddStates(108, 114);
                  break;
               case 104:
                  if ((0x3ff000000000000L & l) != 0L && kind > 3)
                     kind = 3;
                  break;
               case 105:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAdd(104);
                  break;
               case 106:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddTwoStates(104, 105);
                  break;
               case 107:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddStates(115, 117);
                  break;
               case 108:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddStates(118, 121);
                  break;
               case 109:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddStates(122, 126);
                  break;
               case 110:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddStates(127, 132);
                  break;
               case 111:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(111, 112);
                  break;
               case 113:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(113, 114);
                  break;
               case 115:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(115, 116);
                  break;
               case 117:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(117);
                  break;
               case 118:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(118, 119);
                  break;
               case 119:
                  if (curChar == 46)
                     jjCheckNAddStates(133, 136);
                  break;
               case 121:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(122);
                  break;
               case 122:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(122, 123);
                  break;
               case 124:
                  if (curChar == 46)
                     jjCheckNAdd(125);
                  break;
               case 125:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(137, 139);
                  break;
               case 127:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(128);
                  break;
               case 128:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(128, 123);
                  break;
               case 129:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(140, 145);
                  break;
               case 130:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(130, 131);
                  break;
               case 132:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(133);
                  break;
               case 133:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(133, 123);
                  break;
               case 134:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(134, 135);
                  break;
               case 135:
                  if (curChar != 46)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(136, 137);
                  break;
               case 136:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(136, 137);
                  break;
               case 138:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(139);
                  break;
               case 139:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAdd(139);
                  break;
               case 140:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(140, 141);
                  break;
               case 142:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(143);
                  break;
               case 143:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAdd(143);
                  break;
               case 144:
                  if (curChar == 45)
                     jjCheckNAddStates(16, 33);
                  break;
               case 146:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 48)
                     jjCheckNAdd(149);
                  break;
               case 149:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(149);
                  break;
               case 151:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 152:
                  if (curChar == 48)
                     jjCheckNAdd(150);
                  break;
               case 154:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(146, 147);
                  break;
               case 156:
                  if (curChar == 48)
                     jjCheckNAdd(153);
                  break;
               case 157:
                  if (curChar == 48)
                     jjCheckNAdd(158);
                  break;
               case 158:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(158, 159);
                  break;
               case 161:
                  if ((0x3000000000000L & l) != 0L)
                     jjAddStates(148, 149);
                  break;
               case 163:
                  if (curChar == 48)
                     jjCheckNAdd(160);
                  break;
               case 165:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(150, 151);
                  break;
               case 167:
                  if (curChar == 48)
                     jjCheckNAdd(164);
                  break;
               case 168:
                  if (curChar == 48)
                     jjCheckNAdd(169);
                  break;
               case 169:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(169, 170);
                  break;
               case 172:
                  if ((0x3000000000000L & l) != 0L)
                     jjAddStates(152, 153);
                  break;
               case 174:
                  if (curChar == 48)
                     jjCheckNAdd(171);
                  break;
               case 176:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(154, 155);
                  break;
               case 178:
                  if (curChar == 48)
                     jjCheckNAdd(175);
                  break;
               case 179:
                  if (curChar == 48)
                     jjCheckNAdd(180);
                  break;
               case 180:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(180, 181);
                  break;
               case 183:
                  if ((0x3000000000000L & l) != 0L)
                     jjAddStates(156, 157);
                  break;
               case 185:
                  if (curChar == 48)
                     jjCheckNAdd(182);
                  break;
               case 186:
                  if (curChar == 48)
                     jjCheckNAddStates(46, 53);
                  break;
               case 187:
                  if (curChar == 48)
                     jjCheckNAddStates(39, 42);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 45)
                        kind = 45;
                     jjCheckNAddTwoStates(39, 40);
                  }
                  else if (curChar == 94)
                     jjCheckNAddTwoStates(31, 32);
                  break;
               case 188:
               case 39:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAddTwoStates(39, 40);
                  break;
               case 1:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 2:
                  jjCheckNAddStates(43, 45);
                  break;
               case 3:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(43, 45);
                  break;
               case 7:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(158, 159);
                  break;
               case 11:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(36, 38);
                  break;
               case 12:
                  if (curChar == 92)
                     jjAddStates(160, 163);
                  break;
               case 13:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(36, 38);
                  break;
               case 22:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(23);
                  break;
               case 24:
                  if (curChar == 92)
                     jjAddStates(164, 166);
                  break;
               case 25:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAdd(23);
                  break;
               case 30:
                  if (curChar == 94)
                     jjCheckNAddTwoStates(31, 32);
                  break;
               case 31:
                  if ((0x7fffffe84000002L & l) != 0L)
                     jjCheckNAddTwoStates(31, 32);
                  break;
               case 32:
                  if (curChar == 91 && kind > 38)
                     kind = 38;
                  break;
               case 34:
                  jjAddStates(167, 168);
                  break;
               case 38:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAddTwoStates(39, 40);
                  break;
               case 41:
               case 42:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAddTwoStates(40, 42);
                  break;
               case 44:
               case 45:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddTwoStates(45, 46);
                  break;
               case 47:
               case 48:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddTwoStates(46, 48);
                  break;
               case 59:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 70:
                  if (curChar == 90 && kind > 1)
                     kind = 1;
                  break;
               case 112:
                  if ((0x8000000080000L & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 114:
                  if ((0x400000004L & l) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 116:
                  if (curChar == 76 && kind > 9)
                     kind = 9;
                  break;
               case 120:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(169, 170);
                  break;
               case 123:
                  if ((0x4000000040L & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 126:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(171, 172);
                  break;
               case 131:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(173, 174);
                  break;
               case 137:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(175, 176);
                  break;
               case 141:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(177, 178);
                  break;
               case 145:
                  if (curChar == 120)
                     jjCheckNAdd(146);
                  break;
               case 146:
                  if ((0x4200000042L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(146);
                  break;
               case 150:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 153:
                  if (curChar == 120)
                     jjCheckNAdd(154);
                  break;
               case 154:
                  if ((0x4200000042L & l) != 0L)
                     jjCheckNAddTwoStates(154, 155);
                  break;
               case 155:
                  if (curChar == 76 && kind > 14)
                     kind = 14;
                  break;
               case 159:
                  if (curChar == 76 && kind > 15)
                     kind = 15;
                  break;
               case 160:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 162:
                  if (curChar == 76 && kind > 16)
                     kind = 16;
                  break;
               case 164:
                  if (curChar == 120)
                     jjCheckNAdd(165);
                  break;
               case 165:
                  if ((0x4200000042L & l) != 0L)
                     jjCheckNAddTwoStates(165, 166);
                  break;
               case 166:
                  if ((0x8000000080000L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 170:
                  if ((0x8000000080000L & l) != 0L && kind > 18)
                     kind = 18;
                  break;
               case 171:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 173:
                  if ((0x8000000080000L & l) != 0L && kind > 19)
                     kind = 19;
                  break;
               case 175:
                  if (curChar == 120)
                     jjCheckNAdd(176);
                  break;
               case 176:
                  if ((0x4200000042L & l) != 0L)
                     jjCheckNAddTwoStates(176, 177);
                  break;
               case 177:
                  if ((0x400000004L & l) != 0L && kind > 20)
                     kind = 20;
                  break;
               case 181:
                  if ((0x400000004L & l) != 0L && kind > 21)
                     kind = 21;
                  break;
               case 182:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 184:
                  if ((0x400000004L & l) != 0L && kind > 22)
                     kind = 22;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
               case 3:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(43, 45);
                  break;
               case 11:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(36, 38);
                  break;
               case 22:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 34:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(167, 168);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 188 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjStopStringLiteralDfa_1(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_1(int pos, long active0)
{
   return jjMoveNfa_1(jjStopStringLiteralDfa_1(pos, active0), pos + 1);
}
private int jjStartNfaWithStates_1(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_1(state, pos + 1);
}
private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 93:
         return jjStopAtPos(0, 49);
      default :
         return jjMoveNfa_1(0, 0);
   }
}
private int jjMoveNfa_1(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 1;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  kind = 50;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0xffffffffdfffffffL & l) != 0L)
                     kind = 50;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((jjbitVec0[i2] & l2) != 0L && kind > 50)
                     kind = 50;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 1 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   50, 85, 94, 111, 112, 113, 114, 115, 116, 117, 118, 119, 134, 135, 140, 141, 
   111, 113, 115, 117, 147, 148, 152, 156, 157, 163, 167, 168, 174, 178, 179, 185, 
   118, 134, 22, 24, 11, 12, 14, 149, 158, 169, 180, 1, 3, 4, 145, 150, 
   153, 160, 164, 171, 175, 182, 11, 12, 16, 14, 31, 32, 68, 70, 71, 70, 
   71, 77, 78, 70, 71, 79, 80, 81, 82, 83, 84, 78, 70, 71, 78, 70, 
   71, 79, 78, 70, 71, 79, 80, 78, 70, 71, 79, 80, 81, 78, 70, 71, 
   79, 80, 81, 82, 78, 70, 71, 79, 80, 81, 82, 83, 104, 105, 106, 107, 
   108, 109, 110, 104, 105, 106, 104, 105, 106, 107, 104, 105, 106, 107, 108, 104, 
   105, 106, 107, 108, 109, 120, 124, 123, 129, 125, 126, 123, 120, 124, 130, 131, 
   123, 129, 154, 155, 161, 162, 165, 166, 172, 173, 176, 177, 183, 184, 8, 9, 
   13, 15, 17, 20, 25, 26, 28, 34, 36, 121, 122, 127, 128, 132, 133, 138, 
   139, 142, 143, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\173", "\175", null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\164\162\165\145", "\146\141\154\163\145", "\156\165\154\154", "\50", "\51", 
"\133", "\135", "\72", "\54", "\100", null, "\116\141\116", "\53\111\156\146", 
"\55\111\156\146", "\53\102\157\165\156\144", "\55\102\157\165\156\144", null, null, null, null, 
null, "\135", null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
   "IN_CHARSTREAM", 
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 
   -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x67ffffdffffffL, 
};
static final long[] jjtoSkip = {
   0x78000000000000L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[188];
private final int[] jjstateSet = new int[376];
protected char curChar;
/** Constructor. */
public TsonStreamParserImplTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public TsonStreamParserImplTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 188; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   switch(curLexState)
   {
     case 0:
       try { input_stream.backup(0);
          while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
             curChar = input_stream.BeginToken();
       }
       catch (java.io.IOException e1) { continue EOFLoop; }
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
