/* Generated By:JavaCC: Do not edit this line. TsonStreamParserImplConstants.java */
package net.thevpc.tson.impl.parser.javacc;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TsonStreamParserImplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DATETIME = 1;
  /** RegularExpression Id. */
  int DATE = 2;
  /** RegularExpression Id. */
  int TIME = 3;
  /** RegularExpression Id. */
  int REGEX = 4;
  /** RegularExpression Id. */
  int LBRACE = 5;
  /** RegularExpression Id. */
  int RBRACE = 6;
  /** RegularExpression Id. */
  int SHORT = 7;
  /** RegularExpression Id. */
  int BYTE = 8;
  /** RegularExpression Id. */
  int LONG = 9;
  /** RegularExpression Id. */
  int INTEGER = 10;
  /** RegularExpression Id. */
  int INTEGER_H = 11;
  /** RegularExpression Id. */
  int INTEGER_O = 12;
  /** RegularExpression Id. */
  int INTEGER_B = 13;
  /** RegularExpression Id. */
  int LONG_H = 14;
  /** RegularExpression Id. */
  int LONG_O = 15;
  /** RegularExpression Id. */
  int LONG_B = 16;
  /** RegularExpression Id. */
  int SHORT_H = 17;
  /** RegularExpression Id. */
  int SHORT_O = 18;
  /** RegularExpression Id. */
  int SHORT_B = 19;
  /** RegularExpression Id. */
  int BYTE_H = 20;
  /** RegularExpression Id. */
  int BYTE_O = 21;
  /** RegularExpression Id. */
  int BYTE_B = 22;
  /** RegularExpression Id. */
  int FLOAT = 23;
  /** RegularExpression Id. */
  int DOUBLE = 24;
  /** RegularExpression Id. */
  int EXPONENT = 25;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE_STR = 26;
  /** RegularExpression Id. */
  int SINGLE_QUOTE_STR = 27;
  /** RegularExpression Id. */
  int ANTI_QUOTE_STR = 28;
  /** RegularExpression Id. */
  int TRIPLE_DOUBLE_QUOTE_STR = 29;
  /** RegularExpression Id. */
  int TRIPLE_SINGLE_QUOTE_STR = 30;
  /** RegularExpression Id. */
  int TRIPLE_ANTI_QUOTE_STR = 31;
  /** RegularExpression Id. */
  int TRUE = 32;
  /** RegularExpression Id. */
  int FALSE = 33;
  /** RegularExpression Id. */
  int NULL = 34;
  /** RegularExpression Id. */
  int LPAREN = 35;
  /** RegularExpression Id. */
  int RPAREN = 36;
  /** RegularExpression Id. */
  int LBRACK = 37;
  /** RegularExpression Id. */
  int RBRACK = 38;
  /** RegularExpression Id. */
  int COLON = 39;
  /** RegularExpression Id. */
  int OP_PLUS = 40;
  /** RegularExpression Id. */
  int OP_PLUS2 = 41;
  /** RegularExpression Id. */
  int OP_PLUS3 = 42;
  /** RegularExpression Id. */
  int OP_MINUS = 43;
  /** RegularExpression Id. */
  int OP_MINUS2 = 44;
  /** RegularExpression Id. */
  int OP_MINUS3 = 45;
  /** RegularExpression Id. */
  int OP_MUL = 46;
  /** RegularExpression Id. */
  int OP_MUL2 = 47;
  /** RegularExpression Id. */
  int OP_MUL3 = 48;
  /** RegularExpression Id. */
  int OP_DIV = 49;
  /** RegularExpression Id. */
  int OP_DIV3 = 50;
  /** RegularExpression Id. */
  int OP_HAT = 51;
  /** RegularExpression Id. */
  int OP_HAT2 = 52;
  /** RegularExpression Id. */
  int OP_HAT3 = 53;
  /** RegularExpression Id. */
  int OP_REM = 54;
  /** RegularExpression Id. */
  int OP_REM2 = 55;
  /** RegularExpression Id. */
  int OP_REM3 = 56;
  /** RegularExpression Id. */
  int OP_EQ = 57;
  /** RegularExpression Id. */
  int OP_EQ2 = 58;
  /** RegularExpression Id. */
  int OP_EQ3 = 59;
  /** RegularExpression Id. */
  int OP_TILDE = 60;
  /** RegularExpression Id. */
  int OP_TILDE2 = 61;
  /** RegularExpression Id. */
  int OP_TILDE3 = 62;
  /** RegularExpression Id. */
  int OP_LT = 63;
  /** RegularExpression Id. */
  int OP_LT2 = 64;
  /** RegularExpression Id. */
  int OP_LT3 = 65;
  /** RegularExpression Id. */
  int OP_GT = 66;
  /** RegularExpression Id. */
  int OP_GT2 = 67;
  /** RegularExpression Id. */
  int OP_GT3 = 68;
  /** RegularExpression Id. */
  int OP_LTE = 69;
  /** RegularExpression Id. */
  int OP_GTE = 70;
  /** RegularExpression Id. */
  int OP_ASSIGN = 71;
  /** RegularExpression Id. */
  int OP_ASSIGN_EQ = 72;
  /** RegularExpression Id. */
  int OP_MINUS_GT = 73;
  /** RegularExpression Id. */
  int OP_MINUS2_GT = 74;
  /** RegularExpression Id. */
  int OP_EQ_GT = 75;
  /** RegularExpression Id. */
  int OP_EQ2_GT = 76;
  /** RegularExpression Id. */
  int OP_LT_MINUS2 = 77;
  /** RegularExpression Id. */
  int OP_LT_EQ2 = 78;
  /** RegularExpression Id. */
  int OP_PIPE = 79;
  /** RegularExpression Id. */
  int OP_PIPE2 = 80;
  /** RegularExpression Id. */
  int OP_PIPE3 = 81;
  /** RegularExpression Id. */
  int OP_AND = 82;
  /** RegularExpression Id. */
  int OP_AND2 = 83;
  /** RegularExpression Id. */
  int OP_AND3 = 84;
  /** RegularExpression Id. */
  int OP_HASH = 85;
  /** RegularExpression Id. */
  int OP_HASH2 = 86;
  /** RegularExpression Id. */
  int OP_HASH3 = 87;
  /** RegularExpression Id. */
  int OP_HASH4 = 88;
  /** RegularExpression Id. */
  int OP_HASH5 = 89;
  /** RegularExpression Id. */
  int OP_HASH6 = 90;
  /** RegularExpression Id. */
  int OP_HASH7 = 91;
  /** RegularExpression Id. */
  int OP_HASH8 = 92;
  /** RegularExpression Id. */
  int OP_HASH9 = 93;
  /** RegularExpression Id. */
  int OP_HASH10 = 94;
  /** RegularExpression Id. */
  int SEMICOLON = 95;
  /** RegularExpression Id. */
  int SEMICOLON2 = 96;
  /** RegularExpression Id. */
  int COMMA = 97;
  /** RegularExpression Id. */
  int AT = 98;
  /** RegularExpression Id. */
  int AT2 = 99;
  /** RegularExpression Id. */
  int CHARSTREAM_START = 100;
  /** RegularExpression Id. */
  int NAN = 101;
  /** RegularExpression Id. */
  int POS_INF = 102;
  /** RegularExpression Id. */
  int NEG_INF = 103;
  /** RegularExpression Id. */
  int POS_BOUND = 104;
  /** RegularExpression Id. */
  int NEG_BOUND = 105;
  /** RegularExpression Id. */
  int COMMENT = 106;
  /** RegularExpression Id. */
  int ALIAS = 107;
  /** RegularExpression Id. */
  int NAME = 108;
  /** RegularExpression Id. */
  int LETTER = 109;
  /** RegularExpression Id. */
  int DIGIT = 110;
  /** RegularExpression Id. */
  int CHARSTREAM_END = 111;
  /** RegularExpression Id. */
  int CHARSTREAM_PART = 112;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_CHARSTREAM = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<DATETIME>",
    "<DATE>",
    "<TIME>",
    "<REGEX>",
    "\"{\"",
    "\"}\"",
    "<SHORT>",
    "<BYTE>",
    "<LONG>",
    "<INTEGER>",
    "<INTEGER_H>",
    "<INTEGER_O>",
    "<INTEGER_B>",
    "<LONG_H>",
    "<LONG_O>",
    "<LONG_B>",
    "<SHORT_H>",
    "<SHORT_O>",
    "<SHORT_B>",
    "<BYTE_H>",
    "<BYTE_O>",
    "<BYTE_B>",
    "<FLOAT>",
    "<DOUBLE>",
    "<EXPONENT>",
    "<DOUBLE_QUOTE_STR>",
    "<SINGLE_QUOTE_STR>",
    "<ANTI_QUOTE_STR>",
    "<TRIPLE_DOUBLE_QUOTE_STR>",
    "<TRIPLE_SINGLE_QUOTE_STR>",
    "<TRIPLE_ANTI_QUOTE_STR>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"+\"",
    "\"++\"",
    "\"+++\"",
    "\"-\"",
    "\"--\"",
    "\"---\"",
    "\"*\"",
    "\"**\"",
    "\"***\"",
    "\"/\"",
    "\"///\"",
    "\"^\"",
    "\"^^\"",
    "\"^^^\"",
    "\"%\"",
    "\"%%\"",
    "\"%%%\"",
    "\"=\"",
    "\"==\"",
    "\"===\"",
    "\"~\"",
    "\"~~\"",
    "\"~~~\"",
    "\"<\"",
    "\"<<\"",
    "\"<<<\"",
    "\">\"",
    "\">>\"",
    "\">>>\"",
    "\"<=\"",
    "\">=\"",
    "\":=\"",
    "\":==\"",
    "\"->\"",
    "\"-->\"",
    "\"=>\"",
    "\"==>\"",
    "\"<--\"",
    "\"<==\"",
    "\"|\"",
    "\"||\"",
    "\"|||\"",
    "\"&\"",
    "\"&&\"",
    "\"&&&\"",
    "\"#\"",
    "\"##\"",
    "\"###\"",
    "\"####\"",
    "\"#####\"",
    "\"######\"",
    "\"#######\"",
    "\"########\"",
    "\"#########\"",
    "\"##########\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"@\"",
    "\"@@\"",
    "<CHARSTREAM_START>",
    "\"NaN\"",
    "\"+Inf\"",
    "\"-Inf\"",
    "\"+Bound\"",
    "\"-Bound\"",
    "<COMMENT>",
    "<ALIAS>",
    "<NAME>",
    "<LETTER>",
    "<DIGIT>",
    "\"]\"",
    "<CHARSTREAM_PART>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
